<a href="https://colab.research.google.com/github/nicha0524/DPDM2021/blob/main/Seminar_12_09_65.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Import required libraries

In [149]:
import matplotlib.pyplot as plt
%matplotlib inline
import scipy
import scipy.stats
import warnings
warnings.filterwarnings("ignore")

In [150]:
size = 10000
x = scipy.arange(size)

# Generate the data
y = scipy.stats.gamma.rvs(1, size=size, random_state=40)

In [151]:
len(y)

10000

## Obtain the distribution parameters

In [152]:
dist = getattr(scipy.stats, 'gamma')

##### Fit the distribution to the data

In [153]:
param = dist.fit(y)

In [ ]:
#Distribution parameters (e.g. 'a',  for gama distribution)
args = param[:-2]

# Location parameter
loc = param[-2]

# Scale parameter
scale = param[-1]

In [155]:
args


(1.0104532994504662,)

## Probability of failure before time t

In [ ]:
print("Probability of failure before time 40:", round(scipy.stats.gamma.cdf(40, *args, loc=loc, scale=scale)*100,2),"%")

Probability of failure before time 40: 54.55 %


In [ ]:
# Reliability estimation after time t
print("Reliability Estimation at time 40:", round(scipy.stats.gamma.sf(40, *args, loc=loc, scale=scale)*100,2),"%")





Reliability Estimation at time 40: 45.45 %


##Bayesian

##prior distribution P(θ)

In [109]:
theta = scipy.stats.gamma.rvs(2, size=size )

In [110]:
theta

array([2.96160924, 1.18135702, 1.8128751 , ..., 2.5284681 , 1.15867745,
       2.12829563])

In [111]:
import scipy.stats as stats
import numpy as np

In [118]:
prior = stats.gamma.pdf(theta[0], 2)

In [119]:
prior

0.15322061668155523

# likelihood  P(X|θ)

In [79]:
z = scipy.stats.gamma.rvs(1, size=size, random_state=40)*50

In [122]:
likelihood = stats.gamma.pdf(z,1)

In [174]:
likelihood

array([4.24191732e-12, 5.79665866e-02, 1.82783679e-34, ...,
       5.25709387e-03, 1.11405973e-17, 6.91204361e-02])

## Posterior. P(θ|X)

In [124]:

posterior = likelihood[0] * prior

In [125]:
posterior

6.499491878354915e-13

##degradation data

In [147]:
from scipy.sparse.construct import random
data_1 = []

for a in range(1000):
    data = []
    for i in range(10):
        aa = gamma.rvs(2)
        data.append(aa)
    data_1.append(data)
df = pd.DataFrame(data_1)


In [148]:
df

0         1         2         3         4         5         6  \
0    0.400686  1.062207  2.790484  4.400620  3.218440  5.648718  0.992648   
1    0.532120  2.883040  1.342182  0.143803  0.097647  0.912906  0.436875   
2    1.387034  2.192782  1.687327  4.827781  0.166501  1.664702  0.964213   
3    5.308011  0.206982  1.874242  1.863401  3.779928  4.489725  0.995171   
4    1.958229  1.451883  1.194235  1.680916  1.702402  0.878690  3.886395   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.604276  3.163468  2.029285  2.864069  0.701971  0.564196  2.610024   
996  0.247142  2.527066  3.162828  3.193813  1.162687  2.350651  1.427463   
997  1.003988  1.109677  3.351419  4.394415  4.529340  1.382894  2.611358   
998  0.887383  1.665311  3.526729  1.087881  3.450150  4.557145  0.790158   
999  1.292007  3.572661  5.670874  0.809890  4.557468  1.205870  1.148901   

            7         8         9  
0    1.303718  0.635974  2.754500  
1    0.483374  4.770621  1.651314  
2    0.637119  1.046762  5.872965  
3    1.661972  1.300942  5.915247  
4    1.439619  0.801404  0.527840  
..        ...       ...       ...  
995  3.093667  0.647882  1.524790  
996  1.226776  1.772671  1.067965  
997  0.345963  3.400803  2.446681  
998  2.063558  2.506048  0.316820  
999  1.380564  2.041487  3.415123  

[1000 rows x 10 columns]

In [163]:
param = dist.fit(df.iloc[:,1])
arg = param[:-2]

In [167]:
para_ = []
for i in range(10):
    param = dist.fit(df.iloc[:,i])
    arg = param[:-2]
    para_.append(arg)
P_para = pd.DataFrame(para_)

In [168]:
P_para

0
0  1.925540
1  1.955124
2  2.020299
3  2.038789
4  2.005230
5  1.859113
6  1.941216
7  1.956887
8  1.985157
9  2.157034

In [169]:
from scipy.stats import shapiro



In [ ]:
shapiro()

In [170]:
shapiro(para_)

ShapiroResult(statistic=0.9455987215042114, pvalue=0.6168107390403748)

In [172]:
prior = stats.norm.pdf(para_[0])


In [177]:
de_data_2 = df.iloc[:,2]
likelihood = stats.gamma.pdf(de_data_2,2)


In [179]:
posterior = likelihood[0] * prior
posterior

array([0.01070484])

## real time Reliability

In [185]:
print("Probability of failure before time 2 :", round(scipy.stats.gamma.cdf(2, *posterior, loc=loc, scale=scale)*100,2),"%")

Probability of failure before time 2 : 99.95 %


In [187]:
# Reliability estimation after time t
print("Reliability Estimation at time 2:", round(scipy.stats.gamma.sf(2, *posterior, loc=loc, scale=scale)*100,2),"%")



Reliability Estimation at time 2: 0.05 %
